### ISSUE TITLE
install script sets REFBASE to be same as BASE

### ISSUE THREAD

**Issue by hdashnow** [MelbourneGenomics/cpipe#4]
During installation, the install script creates config.groovy and then edits it so that REFBASE is the same as BASE. REFBASE should be:
`
REFBASE="$BASE/hg19"`

I'm pretty sure the problem is in this function, but I'm not familiar enough with sed to fix it:

```
function set_config_variable() {
    NAME="$1"
    VALUE="$2"
    sed -i 's,'$NAME'=".*$,'$NAME'="'$VALUE'",g' $BASE/pipeline/config.groovy
    load_config
}
```

I think this because when I manually run the command:
`sed -i 's,'BASE'=".*$,'BASE'="'/vlsci/VR0193/shared/cpipe'",g' config.groovy`
it replaces 
`REFBASE="$BASE/hg19"`
with 
`REFBASE="/vlsci/VR0193/shared/cpipe"`

**Comment by ssadedin** [comment]
Should be fixed by d033059d1da816740b8b790f6b505dff8598ec94 - thanks!

**Comment by hdashnow** [comment]
I'm still having the same issue after pulling down the latest version of install.sh

**Comment by ssadedin** [comment]
Oops, I'm sorry, please pull & try again.

**Comment by hdashnow** [comment]
Sweet, fixed!
